version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - copyloopvar
    - err113
    - exhaustruct
    - godox
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - mnd
    - nlreturn
    - testpackage
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        all:
          files:
            - $all
          deny:
            - pkg: github.com/xtgo/uuid
              desc: Use `github.com/google/uuid` package for UUIDs instead.
        not-test:
          files:
            - '!$test'
          deny:
            - pkg: github.com/riverqueue/river/internal/dbadaptertest
              desc: Don't use `dbadaptertest` package outside of test environments.
            - pkg: github.com/riverqueue/river/internal/riverinternaltest
              desc: Don't use `riverinternaltest` package outside of test environments.
    forbidigo:
      forbid:
        - pattern: ^assert\.
          msg: Use `require` variants instead.
        - pattern: Fn\b
          msg: Use `Func` suffix for function variables instead.
        - pattern: \bmath\.Max\b
          msg: Use built-in `max` function instead.
        - pattern: \bmath\.Min\b
          msg: Use built-in `min` function instead.
    gomoddirectives:
      replace-local: true
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
    testifylint:
      enable-all: true
      disable:
        - go-require
    varnamelen:
      ignore-names:
        - db
        - eg
        - f
        - i
        - id
        - j
        - mu
        - sb
        - t
        - tt
        - tx
        - wg
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of .(\w+\.Rollback(.*)). is not checked
    paths:
      - third_party$
      - builtin$
      - examples/
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/chariot-giving)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples/
