// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const resourceExpire = `-- name: ResourceExpire :batchexec
UPDATE delta_resource
SET state = 'expired'
WHERE namespace = $1
  AND state NOT IN ('expired', 'deleted') -- Only update resources that are not already expired or deleted
  AND EXTRACT(EPOCH FROM (NOW() - synced_at)) > $2::integer
`

type ResourceExpireBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ResourceExpireParams struct {
	Namespace string
	ExpiryTtl int32
}

// Update the state of delta_resources to 'expired' based on expiryTTL
func (q *Queries) ResourceExpire(ctx context.Context, arg []*ResourceExpireParams) *ResourceExpireBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Namespace,
			a.ExpiryTtl,
		}
		batch.Queue(resourceExpire, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ResourceExpireBatchResults{br, len(arg), false}
}

func (b *ResourceExpireBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ResourceExpireBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const resourceRescheduleExpired = `-- name: ResourceRescheduleExpired :batchmany
UPDATE delta_resource
SET 
    state = 'scheduled',
    errors = array_append(errors, $1::jsonb)
WHERE id IN (
    SELECT id
    FROM delta_resource
    WHERE state = 'expired'
)
RETURNING id, state, attempt, max_attempts, attempted_at, created_at, synced_at, object_id, kind, namespace, object, hash, metadata, tags, errors
`

type ResourceRescheduleExpiredBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) ResourceRescheduleExpired(ctx context.Context, error [][]byte) *ResourceRescheduleExpiredBatchResults {
	batch := &pgx.Batch{}
	for _, a := range error {
		vals := []interface{}{
			a,
		}
		batch.Queue(resourceRescheduleExpired, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ResourceRescheduleExpiredBatchResults{br, len(error), false}
}

func (b *ResourceRescheduleExpiredBatchResults) Query(f func(int, []*DeltaResource, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var items []*DeltaResource
		if b.closed {
			if f != nil {
				f(t, items, ErrBatchAlreadyClosed)
			}
			continue
		}
		err := func() error {
			rows, err := b.br.Query()
			if err != nil {
				return err
			}
			defer rows.Close()
			for rows.Next() {
				var i DeltaResource
				if err := rows.Scan(
					&i.ID,
					&i.State,
					&i.Attempt,
					&i.MaxAttempts,
					&i.AttemptedAt,
					&i.CreatedAt,
					&i.SyncedAt,
					&i.ObjectID,
					&i.Kind,
					&i.Namespace,
					&i.Object,
					&i.Hash,
					&i.Metadata,
					&i.Tags,
					&i.Errors,
				); err != nil {
					return err
				}
				items = append(items, &i)
			}
			return rows.Err()
		}()
		if f != nil {
			f(t, items, err)
		}
	}
}

func (b *ResourceRescheduleExpiredBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
